name: Android Setup
description: Configure JDK and Android SDK to execute Android tasks in CI

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept licenses
      shell: bash
      run: sdkmanager --licenses || true

    - name: Install required SDK packages
      shell: bash
      run: |
        sdkmanager --install \
          "platform-tools" \
          "emulator" \
          "cmdline-tools;latest" \
          "build-tools;30.0.3" \
          "platforms;android-30" \
          "system-images;android-30;google_apis_playstore;x86"
