name: Generate Debug APK
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Android Setup
        uses: ./.github/actions/android-setup

#      - name: Run detekt
#        run: ./gradlew detekt
#
#      - name: Run lint
#        run: ./gradlew lint
#
#      - name: Run unit test
#        run: ./gradlew testDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
