name: Run tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Android Setup
        uses: ./.github/actions/android-setup

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run lint
        run: ./gradlew lint

      - name: Run unit test
        run: ./gradlew testDebugUnitTest
