name: Run Screenshot Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  screenshot-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Run screenshot tests on stable emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86
          profile: Nexus 5
          headless: true
          disable-animations: true
          disable-linux-hw-accel: true
          emulator-boot-timeout: 360
          script: ./gradlew executeScreenshotTests

      - name: Upload screenshots as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-test-results
          path: |
            **/build/outputs/shot/**/screenshots/
            **/build/reports/shot/
