name: Run tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Android Setup
        uses: ./.github/actions/android-setup

#      - name: Run detekt
#        run: ./gradlew detekt
#
#      - name: Run lint
#        run: ./gradlew lint
#
#      - name: Run unit test
#        run: ./gradlew testDebugUnitTest

      - name: Start emulator and run screenshot tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86_64
          emulator-build: 9129289
          emulator-options: -no-audio -no-boot-anim
          disable-animations: true
          emulator-timeout: 600 
          script: ./gradlew executeScreenshotTests -Pshot

      - name: Verify screenshots
        run: ./gradlew verifyScreenshotTests -Pshot

      # Opcional para depuración
      - name: Check ADB devices (debug)
        if: failure()
        run: adb devices