name: Run Instrumented Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required SDK packages
        run: |
          sdkmanager --install \
            "platform-tools" \
            "emulator" \
            "cmdline-tools;latest" \
            "build-tools;34.0.0" \
            "platforms;android-34" \
            "system-images;android-34;google_apis;x86_64"

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd \
            --name testEmulator \
            --package "system-images;android-34;google_apis;x86_64" \
            --device "pixel"

      - name: Launch emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd testEmulator -no-audio -no-window -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Disable system animations
        run: |
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Run instrumented tests
        run: ./gradlew connectedDebugAndroidTest

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/androidTests/connected/

      - name: Upload screenshots (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: app/screenshots/
