name: Run Screenshot Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  screenshot-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: AVD Cache
        uses: actions/cache@v4
        with:
          path: ~/.android/avd
          key: avd-${{ runner.os }}-api30
          restore-keys: |
            avd-${{ runner.os }}-

      - name: Create AVD and start emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -no-audio -gpu swiftshader_indirect &
        shell: bash

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            sleep 5
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
            echo "Waiting for emulator to boot... ($boot_completed)"
          done
          adb shell input keyevent 82
        shell: bash

      - name: Run screenshot tests
        run: ./gradlew executeScreenshotTests
