name: Run tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Android Setup
        uses: ./.github/actions/android-setup

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run lint
        run: ./gradlew lint

      - name: Run unit test
        run: ./gradlew testDebugUnitTest

      - name: Enable KVM group perms (required for hardware acceleration)
        run: |
          sudo chown root /dev/kvm
          sudo chmod 666 /dev/kvm

      - name: Launch emulator & Run screenshot tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86_64
          profile: Nexus 5
          script: ./gradlew app:connectedDebugAndroidTest
          disable-animations: true
          disable-spellchecker: true
          emulator-options: "-no-window -no-audio -gpu swiftshader_indirect"
