name: Version catalog update

on:
  schedule:
    - cron: '0 4 1 * *' # At 04:00 AM on the 1st of each month
  workflow_dispatch:

jobs:
  version-catalog-update:
    name: Run versionCatalogUpdate and create PR
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run versionCatalogUpdate
        run: ./gradlew versionCatalogUpdate

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Branch Name
        run: echo "BRANCH_NAME=version-catalog-update-$(date +%s%3N)" >> $GITHUB_ENV

      - name: Create and Commit Changes
        run: |
          git checkout -b "$BRANCH_NAME"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "SKIP_PR=true" >> $GITHUB_ENV
          else
            git commit -m "Automated version catalog update"
            echo "SKIP_PR=false" >> $GITHUB_ENV
          fi

      - name: Push Changes
        if: env.SKIP_PR != 'true'
        run: git push origin "$BRANCH_NAME"

      - name: Create Pull Request (via GitHub REST API)
        if: env.SKIP_PR != 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Creating pull request from $BRANCH_NAME to main"
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/pulls \
            -d @- <<EOF
          {
            "title": "Automated version catalog update",
            "head": "$BRANCH_NAME",
            "base": "main",
            "body": "Automated version catalog update powered by [littlerobots/version-catalog-update-plugin](https://github.com/littlerobots/version-catalog-update-plugin) plugin."
          }
          EOF