name: Version catalog update

on:
  schedule:
    - cron: '0 4 1 * *' # At 04:00 AM, on 1st of the month
  workflow_dispatch:

jobs:
  version-catalog-update:
    name: Run versionCatalogUpdate and create PR
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run versionCatalogUpdate
        run: ./gradlew versionCatalogUpdate

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit and push changes if needed
        run: |
          TIMESTAMP=$(date +%s%3N)
          BRANCH_NAME="version-catalog-update-${TIMESTAMP}"
          echo "Generated branch name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          echo "Checking git status..."
          git status
          git diff

          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected. Committing..."
            git checkout -b "$BRANCH_NAME"
            git add .
            git commit -m "Automated version catalog update"
            git push origin "$BRANCH_NAME"
            echo "SKIP_PR=false" >> $GITHUB_ENV
          else
            echo "No changes to commit."
            echo "SKIP_PR=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.SKIP_PR != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "Automated version catalog update"
          body: "Automated version catalog update powered by [littlerobots/version-catalog-update-plugin](https://github.com/littlerobots/version-catalog-update-plugin) plugin."
          delete-branch: true
