name: Version catalog update

on:
  schedule:
    - cron: '0 4 1 * *' #At 04:00 AM, on 1st of the month
  workflow_dispatch:

jobs:
  version-catalog-update:
    name: Run versionCatalogUpdate and create PR
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run versionCatalogUpdate
        run: ./gradlew versionCatalogUpdate

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "bot@users.noreply.github.com"

      - name: Commit changes
        run: |
          git checkout -b version-catalog-update
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          TIMESTAMP=$(date +%s%3N)
          BRANCH_NAME="version-catalog-update-${TIMESTAMP}"
          
          git checkout -b "$BRANCH_NAME"
          
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Automated version catalog update"
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          else
            echo "No changes to commit"
            echo "SKIP_PR=true" >> $GITHUB_ENV
          fi

      - name: Push changes
        if: env.SKIP_PR != 'true'
        run: git push origin $BRANCH_NAME

      - name: Create Pull Request
        if: env.SKIP_PR != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.BRANCH_NAME }}
          title: "Automated version catalog update"
          body: "Automated version catalog update powered by [littlerobots/version-catalog-update-plugin](https://github.com/littlerobots/version-catalog-update-plugin) plugin."
          delete-branch: true